<?php

namespace TDN\Bundle\NanaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NanaHobbyImageProxyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NanaHobbyImageProxyRepository extends EntityRepository
{
}
