<?php

namespace TDN\Bundle\ConcoursBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConcoursQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConcoursQuestionRepository extends EntityRepository
{
}
