<?php

namespace TDN\Bundle\DossierRedactionBundle\Entity;

use Doctrine\ORM\EntityRepository;

use TDN\Bundle\DocumentBundle\Entity\DocumentRepository;

/**
 * DossierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DossierRepository extends DocumentRepository
{
	public function findLast ()
		{
			$qb = $this->createQueryBuilder('c');
			$query = $qb->select('c')
				->where($qb->expr()->like('c.statut', $qb->expr()->literal('DOSSIER_PUBLIE')))
				->orderby('c.datePublication', 'DESC')
				->setMaxResults(1)
				->getQuery();

			return $query->getResult();
		}

	public function findMostRecent ($limite, $panel = NULL) {
		return parent::findMostRecentDocument($limite, 'DOSSIER_PUBLIE', $panel);
	}

	public function findPage ($page, $size = 50, $all = true) {
		$offset = ($page - 1) * $size;
		$qb = $this->createQueryBuilder('u');
		$query = $qb->select('u');
		if ($all !== true && is_numeric($all)) {
			$query = $query->where($qb->expr()->eq('u.lnAuteur', ':id'))
						   ->setParameter('id', $all);
		}
	    $query = $query->orderBy('u.datePublication', 'DESC')
	        		   ->setFirstResult($offset);
	    if ($size !== 0) {
	    	$query = $query->setMaxResults($size);
	    }
	    $query = $query->getQuery();
	    // ->where($qb->expr()->like('u.statut', $qb->expr()->literal('ARTICLE_PUBLIE')))

	     $last = $query->getResult();
	     return $last;
	}

	public function findByRubrique ($rubrique, $limite, $offset) {
		$qb = $this->createQueryBuilder('v');
		$query = $qb->select('v')
					->innerjoin('v.rubriques', 'r')
					->leftjoin('r.rubriqueParente', 'p')
	        		->where($qb->expr()->andX(
	        			$qb->expr()->like('v.statut', $qb->expr()->literal('DOSSIER_PUBLIE')),
	        			$qb->expr()->orX(
	        				$qb->expr()->like('r.slug', ':rubrique'),
	        				$qb->expr()->like('p.slug', ':rubrique')
	        			)))
	        		->setParameter('rubrique', $rubrique)
	        		->orderBy('v.datePublication', 'DESC')
	        		->groupBy('v.idDocument')
	        		->setFirstResult($offset*($limite-1))
	        		->setMaxResults($limite)
	        		->getQuery()
	        		->useResultCache(true, 900);

	    /*$query = "SELECT DISTINCT D FROM `Document` D JOIN DocumentThemes T ON T.for_document = D.id 
	    JOIN DocumentRubrique R1 ON T.for_document = R1.id JOIN DocumentRubrique R2 ON R1.rubriqueParente_id = R2.id 
	    WHERE D.typeDocument = 'video' AND D.statut LIKE 'VIDEO_PUBLIEE' AND (R1.slug LIKE '$rubrique' OR R2.slug LIKE '$rubrique')
	    LIMIT ($limite, $offset)";
	    */
	     $last = $query->getResult();
	     return $last;
	}


}

