<?php

namespace TDN\Bundle\NewsletterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AbonnesNewsletterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbonnesNewsletterRepository extends EntityRepository
{
	   public function findMailPacket ($debut=  '0', $fin = 'zzzzz') {

        $qb = $this->createQueryBuilder('u');
        $query = $qb->select('u')
                    ->where($qb->expr()->andX(
                        $qb->expr()->gte('u.email', ':debut'),
                        $qb->expr()->lt('u.email', ':fin')
                    ))
                    ->setParameter('debut', $debut)
                    ->setParameter('fin', $fin)
                    ->getQuery()
                    ->useResultCache(true, 3600);

        $resultats = $query->getResult();
        return $resultats;
    }

    public function findAnonymesNewsletter ($debut = 0, $limite = 300) {
        $qb = $this->createQueryBuilder('u');
        $query = $qb->select('u')
                    ->setFirstResult($debut)
                    ->setMaxResults($limite)
                    ->getQuery()
                    ->useResultCache(true, 72000);

        $resultats = $query->getResult();
        return $resultats;
    }

}
