<?php

namespace TDN\Bundle\NewsletterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsletterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterRepository extends EntityRepository
{

	public function searchReady()
	{
        $now = new \DateTime;
		$qb = $this->createQueryBuilder('u');
		$qexpr = $qb->expr();
		$query = $qb->select('u')
					->where($qexpr->andX(
						   		$qexpr->lt('u.datePublication', ':now'),
						   		$qexpr->like('u.statut', ':prete')
						   	))
						   ->setParameter('now', $now)
						   ->setParameter('prete', 'LETTRE_PREPARATION')
						   ->orderBy('u.datePublication', 'DESC')
	        		   	   ->setMaxResults(1)
	        		       ->getQuery()
	        		       ->useResultCache(true);

	     $last = $query->getResult();
	     if (!empty($last)) {
		     return $last[0];
	     } else {
	     	return false;
	     }
	}
}
