<?php

namespace TDN\Bundle\CauseuseBundle\Entity;

use Doctrine\ORM\EntityRepository;

use TDN\Bundle\DocumentBundle\Entity\DocumentRepository;


/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends DocumentRepository {

	public function findMostRecent ($limite, $panel = NULL, $tree = false) {
		return parent::findMostRecentDocument ($limite, 'QUESTION_PUBLIEE', $panel, $tree = false);
   }

   public function findMostLiked ($limite, $panel = NULL) {
      return parent::findMostLikedDocument ($limite, 'QUESTION_PUBLIEE', $panel);
   }
}
