<?php

namespace TDN\Bundle\DocumentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentRubriqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRubriqueRepository extends EntityRepository {
	
	public function findTop () {
		$qb = $this->createQueryBuilder('u');

		$query = $qb->select('u')
					->where('u.rubriqueParente is NULL')
					->orderBy('u.titre', 'ASC')
					->getQuery();

	     $top = $query->getResult();
	     return $top;
	}

	public function getChildren ($slug)
	{
		$qb = $this->createQueryBuilder('u');
		$qexpr = $qb->expr();
		$query = $qb->select('u.slug')
					->innerjoin('u.rubriqueParente', 'r')
					->where($qexpr->like('u.slug', ':rubrique'))
					->setParameter('rubrique', $slug)
					->getQuery()
	        		->useResultCache(true);

	    $panel = $query->getResult();
	    return $panel;
	}
}