<?php

namespace TDN\Bundle\DocumentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentTypeRepository extends EntityRepository
{
}
